T1_Roman_Oscar/Models/ErrorViewModel.cs
namespace T1_Roman_Oscar.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

T1_Roman_Oscar/Models/Libro.cs
using System.ComponentModel.DataAnnotations;

namespace T1_Roman_Oscar.Models
{
    public class Libro
    {
        [Key]
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Autor {  get; set; }
        public string Tema { get; set; }
        public string Editorial { get; set; }
        public int AnioPublicacion { get; set; }
        public int Paginas {  get; set; }
        public string Categoria { get; set; }
        public string Material {  get; set; }
        public int Copias { get; set; }
    }
}

T1_Roman_Oscar/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using T1_Roman_Oscar.Models;

namespace T1_Roman_Oscar.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

T1_Roman_Oscar/Controllers/LibroController.cs
using Microsoft.AspNetCore.Mvc;
using T1_Roman_Oscar.Datos;
using T1_Roman_Oscar.Models;

namespace T1_Roman_Oscar.Controllers
{
    public class LibroController : Controller
    {
        readonly ApplicationDbContext _db;

        public LibroController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Libro> lista = _db.Libro;
            return View(lista);
        }
    }
}

T1_Roman_Oscar/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

T1_Roman_Oscar/Views/Libro/Index.cshtml
@model IEnumerable<T1_Roman_Oscar.Models.Libro>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- <h1>Index</h1> -->
<div class="text-center">
    <h1 class="display-4">Bienvenido a la estantería de libros</h1>
</div>

<div class="container pt-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Libros</h2>
        </div>

        <div class="col-6">
        </div>
    </div>

    <br />
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Título</th>
                    <th>Autor</th>
                    <th>Tema</th>
                    <th>Editorial</th>
                    <th>Año de Publicacion</th>
                    <th>Paginas</th>
                    <th>Categoría</th>
                    <th>Material</th>
                    <th>Copias</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th width="5%">@item.Id</th>
                        <th width="10%">@item.Titulo</th>
                        <th width="10%">@item.Autor</th>
                        <th width="10%">@item.Tema</th>
                        <th width="10%">@item.Editorial</th>
                        <th width="10%">@item.AnioPublicacion</th>
                        <th width="5%">@item.Paginas</th>
                        <th width="10%">@item.Categoria</th>
                        <th width="10%">@item.Material</th>
                        <th width="10%">@item.Copias</th>
                        <th>

                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Libro" asp-action="Editar" asp-route-Id="@item.Id" class="btn btn-primary mx-2">Editar</a>
                                <a asp-controller="Libro" asp-action="Eliminar" asp-route-Id="@item. Id" class="btn btn-danger mx-2">Eliminar</a>
                            </div>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p class="text-primary">No hay registros de Categoria</p>
    }

</div>

T1_Roman_Oscar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - T1_Roman_Oscar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/T1_Roman_Oscar.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">T1_Roman_Oscar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="Index">Libro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - T1_Roman_Oscar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>